### ISSUE TITLE
docker.apache keeps on resetarting state

### ISSUE THREAD

**Issue by vasqueeg** [vagnercardosoweb/vcwebnetworks-docker-php#11]
Hello @vagnercardosoweb,

Noticed that "docker.apache" container keeps on restarting state.  Any advise on how to resolve this?  See below:
-------------------------------------------
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                        PORTS                                                                      NAMES
ef3cfb55d3ed   docker-php8-apache                  "httpd-foreground"       11 days ago     Restarting (1) 1 second ago                                                                              docker.apache
970e42fc557f   phpmyadmin                          "/docker-entrypoint.…"   11 days ago     Up 11 days                    0.0.0.0:8080->80/tcp, :::8080->80/tcp                                      docker.phpmyadmin
1a6dc995af28   docker-php8-php                     "docker-php-entrypoi…"   11 days ago     Up 11 days                    9000/tcp                                                                   docker.php
b2c048c34e46   mysql:5                             "docker-entrypoint.s…"   11 days ago     Up 11 days                    3306/tcp, 33060/tcp, 0.0.0.0:13306->13306/tcp, :::13306->13306/tcp         docker.mysql
-------------------------------------------

Thank you in advance!

**Comment by vagnercardosoweb** [comment]
Hello @vasqueeg 

What logs are given in the apache container?

**Comment by vasqueeg** [comment]
Hello @vagnercardosoweb,

Below is the docker logs:
`(2)No such file or directory: AH02291: Cannot access directory '/var/www/app/docker/apache/logs/' for main error log
AH00014: Configuration check failed
(2)No such file or directory: AH02291: Cannot access directory '/var/www/app/docker/apache/logs/' for main error log
AH00014: Configuration check failed
(2)No such file or directory: AH02291: Cannot access directory '/var/www/app/docker/apache/logs/' for main error log
AH00014: Configuration check failed
(2)No such file or directory: AH02291: Cannot access directory '/var/www/app/docker/apache/logs/' for main error log
AH00014: Configuration check failed
(2)No such file or directory: AH02291: Cannot access directory '/var/www/app/docker/apache/logs/' for main error log
AH00014: Configuration check failed
`

**Comment by vagnercardosoweb** [comment]
@vasqueeg 

The error says that the "logs" folder does not exist, check if you have created it within "docker/apache/logs", if not, create the folder and try again.

If this is not the case, let me know and I will carry out a more in-depth test to analyze it.
