### ISSUE TITLE
PHP Yaml Module still not loaded

### ISSUE THREAD

**Issue by vasqueeg** [vagnercardosoweb/vcwebnetworks-docker-php#12]
Hello @vagnercardosoweb,

This is inline with the issue I've opened under https://github.com/vagnercardosoweb/docker-php8/issues/10 wherein I've already pulled the changes to my machine and down/up my docker.  However, PHP Yaml module is still not present in the loaded PHP modules.  I've pasted the output in the link above.  Any steps that I've missed?  TIA!

**Comment by vagnercardosoweb** [comment]
@vasqueeg 

Try to rebuild your images. There would be no additional steps.

`docker compose up --build`.

In the latter case, clean your images, containers and perform `docker compose up --build` again.

**Comment by vasqueeg** [comment]
It's good now!  I can see yaml module is installed / enabled! thanks for the quick action!
