### ISSUE TITLE
Make x-debug connect to external remote 

### ISSUE THREAD

**Issue by Iyadhfaleh** [vagnercardosoweb/vcwebnetworks-docker-php#13]
Hello , 

Recently I tested the stack and it worked very well , but I had a problem when I'm trying to use x-debug . Also As a PHP developer I prefer that XDEBUG disabled by default and enable it when needing .

I prepared a PR for this proposition .

**Comment by vagnercardosoweb** [comment]
@Iyadhfaleh 

Ok, feel free to open the PR. I kept it as the default, in case anyone who uses it in production or doesn't like it, they would deactivate it.

One question: What would be the problem encountered?

**Comment by Iyadhfaleh** [comment]
@vagnercardosoweb For the problem , x-debug can't reach clients listeners outside the container like PHPStorm .
I couldn't push the PR because I don't have enough permissions to do that

**Comment by vagnercardosoweb** [comment]
@Iyadhfaleh 

Open a PR, which I will review. 

I don't understand about permission.

**Comment by vagnercardosoweb** [comment]
closed, due to lack of activation.
